# Generated by Django 3.2 on 2022-05-04 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
