# Generated by Django 3.2 on 2022-04-08 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('code', models.CharField(max_length=100, null=True)),
                ('id_control_variable', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
            ],
            options={
                'db_table': 'control_variable',
            },
        ),
        migrations.CreateModel(
            name='DetectionMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('code', models.CharField(max_length=100, null=True)),
                ('id_detection_mode', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
            ],
            options={
                'db_table': 'detection_mode',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('code', models.CharField(max_length=100, null=True)),
                ('id_driver', models.CharField(max_length=50, null=True)),
                ('nro_identification', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
            ],
            options={
                'db_table': 'driver',
            },
        ),
        migrations.CreateModel(
            name='OperationPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('code', models.CharField(max_length=100, null=True)),
                ('id_operation_place', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
            ],
            options={
                'db_table': 'operation_place',
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, null=True)),
                ('codigo', models.CharField(max_length=100, null=True)),
                ('id_symptom', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
            ],
            options={
                'db_table': 'symptom',
            },
        ),
        migrations.CreateModel(
            name='Relief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(verbose_name='date creation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='administremos.driver', verbose_name='driver')),
            ],
            options={
                'db_table': 'relief',
            },
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_active', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200, null=True)),
                ('code', models.CharField(max_length=100, null=True)),
                ('plate', models.CharField(max_length=100, null=True)),
                ('brand', models.CharField(max_length=100, null=True)),
                ('model', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bus', to='administremos.driver')),
            ],
            options={
                'db_table': 'bus',
            },
        ),
    ]
