# Generated by Django 3.2 on 2022-04-05 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administremos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='id_active',
            new_name='id_activo',
        ),
    ]
