# Generated by Django 3.2 on 2022-04-24 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administremos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='date_relief',
            field=models.DateTimeField(null=True, verbose_name='fecha de relevo'),
        ),
        migrations.AddField(
            model_name='driver',
            name='relief',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administremos.driver'),
        ),
    ]
