# Generated by Django 3.2 on 2022-04-09 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administremos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bus', to='administremos.driver'),
        ),
        migrations.AlterField(
            model_name='relief',
            name='driver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relief', to='administremos.driver', verbose_name='driver'),
        ),
        migrations.CreateModel(
            name='Novelty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('start_hour', models.TimeField(verbose_name='start hour')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('end_hour', models.TimeField(verbose_name='end hour')),
                ('description', models.TextField(verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus', to='administremos.bus')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novelty', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
        ),
    ]
