# Generated by Django 3.2 on 2022-04-10 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administremos', '0002_auto_20220409_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novelty',
            name='end_hour',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='end hour'),
        ),
        migrations.AlterField(
            model_name='novelty',
            name='start_hour',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='start hour'),
        ),
    ]
