# Generated by Django 3.2 on 2022-04-05 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administremos', '0002_rename_id_active_bus_id_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administremos.bus', verbose_name='bus')),
            ],
            options={
                'db_table': 'bus_driver',
            },
        ),
        migrations.AlterModelTable(
            name='empleado',
            table='driver',
        ),
        migrations.CreateModel(
            name='Relief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administremos.busdriver', verbose_name='driver')),
            ],
            options={
                'db_table': 'relief',
            },
        ),
        migrations.AddField(
            model_name='busdriver',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administremos.empleado', verbose_name='empleado'),
        ),
    ]
