# Generated by Django 3.2 on 2022-04-25 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administremos', '0003_alter_driver_relief'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReliefDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('end_date', models.DateTimeField(verbose_name='end date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relief_driver', to='administremos.driver', verbose_name='driver')),
                ('relief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_relief', to='administremos.driver', verbose_name='driver')),
            ],
            options={
                'db_table': 'relief_driver',
            },
        ),
    ]
