# Generated by Django 3.2 on 2022-04-25 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administremos', '0005_auto_20220425_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='date_relief',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='relief',
        ),
    ]
