# Generated by Django 3.2 on 2022-04-26 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administremos', '0006_auto_20220425_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReliefBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='start date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='end date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relief_bus', to='administremos.bus', verbose_name='bus')),
                ('relief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_relief', to='administremos.driver', verbose_name='driver')),
            ],
            options={
                'db_table': 'relief_bus',
            },
        ),
    ]
