# Generated by Django 3.2 on 2022-04-27 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administremos', '0008_alter_reliefbus_relief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reliefbus',
            name='relief',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_relief', to='administremos.bus', verbose_name='bus'),
        ),
    ]
