# Generated by Django 3.2 on 2022-05-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administremos', '0010_auto_20220502_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='reliefdriver',
            name='has_relief',
            field=models.BooleanField(default=False, verbose_name='has relief?'),
        ),
    ]
