# Generated by Django 3.2 on 2022-05-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administremos', '0011_reliefdriver_has_relief'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reliefdriver',
            name='has_relief',
        ),
        migrations.AddField(
            model_name='driver',
            name='has_relief',
            field=models.BooleanField(default=False, verbose_name='has relief?'),
        ),
    ]
