version: '3.9'

services:
  web:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: transturismo
    volumes:
      - .:/code
    ports:
      - "8000:8000"
