# Generated by Django 3.2 on 2022-05-05 09:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contratos', '__first__'),
        ('administremos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name day')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='days_author', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'db_table': 'day',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=300, verbose_name='name service or route')),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('end_date', models.DateTimeField(verbose_name='end date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_contract', to='contratos.fixedcontract')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_author', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'db_table': 'service',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_schedule', models.CharField(choices=[('SACA', 'Saca'), ('ENTRA', 'Entra')], default='SACA', max_length=30, verbose_name='schedule type')),
                ('start_hour', models.TimeField(default=datetime.time(0, 0), verbose_name='start hour')),
                ('end_hour', models.TimeField(default=datetime.time(0, 0), verbose_name='end hour')),
                ('quantity_fleet', models.IntegerField(default=1, verbose_name='quantity fleet')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('bus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='schedule', to='administremos.bus', verbose_name='bus')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='schedules_author', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('days', models.ManyToManyField(related_name='schedule_day', to='services.Day')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules_service', to='services.service')),
            ],
            options={
                'db_table': 'schedule',
                'ordering': ('-created_at',),
            },
        ),
    ]
