# Generated by Django 3.2 on 2022-03-31 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=300, verbose_name='name service or route')),
                ('type_route', models.CharField(choices=[('DEPARTURE', 'Salida'), ('ARRIVAL', 'Llegada')], default='DEPARTURE', max_length=30, verbose_name='route type')),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('end_date', models.DateTimeField(verbose_name='end date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_contract', to='contratos.contract')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_hour', models.DateTimeField(verbose_name='start date')),
                ('end_hour', models.DateTimeField(verbose_name='end hour')),
                ('quantity_fleet', models.IntegerField(verbose_name='quantity fleet')),
                ('day', models.CharField(max_length=2, verbose_name='day')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules_service', to='services.service')),
            ],
        ),
    ]
