# Generated by Django 3.2 on 2022-04-05 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administremos', '0002_rename_id_active_bus_id_activo'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='bus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='schedule', to='administremos.bus', verbose_name='bus'),
        ),
    ]
