# Generated by Django 3.2 on 2022-04-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_schedule_bus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='quantity_fleet',
            field=models.IntegerField(default=1, verbose_name='quantity fleet'),
        ),
    ]
