# Generated by Django 3.2 on 2022-05-03 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20220503_1937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ('-created_at',)},
        ),
    ]
