# Generated by Django 3.2 on 2022-05-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_schedule_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='day',
        ),
        migrations.AddField(
            model_name='schedule',
            name='day',
            field=models.ManyToManyField(related_name='schedule_day', to='services.Day'),
        ),
    ]
