# Generated by Django 3.2 on 2022-05-04 00:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20220503_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='day',
            new_name='days',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_hour',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='start hour'),
        ),
    ]
