# Generated by Django 3.2 on 2022-04-21 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occasionalcontract',
            name='destiny',
            field=models.CharField(max_length=200, verbose_name='destiny'),
        ),
    ]
