# Generated by Django 3.2 on 2022-04-25 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_alter_occasionalcontract_destiny'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixedcontract',
            options={'ordering': ('created_at',)},
        ),
    ]
