# Generated by Django 3.2 on 2022-04-28 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_alter_fixedcontract_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedcontract',
            name='contractor_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contract_for_fixed', to='contratos.usercontractor', verbose_name='contractor for'),
        ),
    ]
